version: '3.6'
services:
  java:
    build:
      context: ./docker/java/
      dockerfile: ./Dockerfile
    tty: true
    volumes:
    - ./:/prj
    environment:
    - HOST_UID=${HOST_UID:-1000}
    - HOST_GID=${HOST_GID:-1000}
    - CONTAINER_USER=${CONTAINER_USER:-user}
    - CONTAINER_GROUP=${CONTAINER_GROUP:-user}
    