version: '3.6'
services:
  java:
    container_name: agile-software-java
    build:
      context: ./docker/java/
      dockerfile: ./Dockerfile
    tty: true
    volumes:
    - .:/workspace
    - ~/.ssh:/home/${CONTAINER_USER:-user}/.ssh:ro
    working_dir: /workspace